name: Build documentation

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  web-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: MineInAbyss/publish-action@develop
        with:
          build-tasks: 'jsDist docsGenerate'
          publish-github-release: 'false'

      - name: Upload js distribution
        uses: actions/upload-artifact@v4
        with:
          name: web-demo
          path: dist/js

      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: out

      - name: Stop gradle daemon
        run: ./gradlew --stop

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: [ web-demo ]
    runs-on: ubuntu-latest
    steps:
      - name: Download web demo artifact
        uses: actions/download-artifact@v4
        with:
          name: web-demo
          path: dir

      - name: Download docs artifact
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: dir/docs

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Package and upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dir

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
